#Expyriment 0.8.0 (Python 2.7.12), .xpe-file, coding: UTF-8
#date: Tue Oct 11 2016 11:59:24
#sha1: 23c69c
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: ('Linux', 'GNOLO-T450S', '4.4.0-38-generic', '#57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016', 'x86_64', 'x86_64')
Time,Type,Event,Value,Detail,Detail2
601,Picture,loaded,./img/configuration_1.jpg
634,stderr,received,'Traceback (most recent call last):'
634,stderr,received,'  File "/usr/lib/pycharm-community/helpers/pydev/pydevd.py", line 1580, in <module>'
635,stderr,received,"    globals = debugger.run(setup['file'], None, None, is_module)"
635,stderr,received,'  File "/usr/lib/pycharm-community/helpers/pydev/pydevd.py", line 964, in run'
635,stderr,received,'    pydev_imports.execfile(file, globals, locals)  # execute the script'
635,stderr,received,'  File "/home/carmine/Code/cp-stim-pro/config_fmri.py", line 35, in <module>'
635,stderr,received,'    trials[condition].append(t) # add the trial t to the trials for the condition "condition"'
635,stderr,received,"NameError: name 'condition' is not defined"
